{
 "title": "Spark dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "juju_model", "label": "juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "label": "juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},job)"
    }
   },
   { "name": "spark_job_id", "label": "Spark Job ID ", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Driver Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Block Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Block Manager Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "BlockManager_memory_maxMem_MB{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Max Memory (MB)"
    },
    {
     "expr": "BlockManager_memory_maxOffHeapMem_MB{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Max Off Heap Memory (MB)"
    },
    {
     "expr": "BlockManager_memory_maxOnHeapMem_MB{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Max On Heap Memory (MB)"
    },
    {
     "expr": "BlockManager_memory_remainingMem_MB{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Remaining Memory (MB)"
    }
   ]
  },
  {
   "title": "Block Manager Disk Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "BlockManager_disk_diskSpaceUsed_MB{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Disk Memory (MB)"
    }
   ]
  },
  { "title": "Hive External Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Hive External Catalog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "HiveExternalCatalog_fileCacheHits{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "File Cache Hits"
    },
    {
     "expr": "HiveExternalCatalog_filesDiscovered{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "File Discovered"
    },
    {
     "expr": "HiveExternalCatalog_hiveClientCalls{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Client Calls"
    },
    {
     "expr": "HiveExternalCatalog_parallelListingJobCount{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Parallel Listing Jobs"
    },
    {
     "expr": "HiveExternalCatalog_partitionsFetched{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Partitions Fetched"
    }
   ]
  },
  {
   "title": "Dag Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "DAGScheduler_job_activeJobs{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Active Jobs"
    },
    {
     "expr": "DAGScheduler_job_allJobs{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "All Jobs"
    }
   ]
  }
 ]
}