{
 "title": "Spark dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "juju_model", "label": "juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "label": "juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},job)"
    }
   },
   { "name": "spark_job_id", "label": "Spark Job ID ", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Driver Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Block Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Manager Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "BlockManager_memory_maxMem_MB{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Max Memory (MB)"
      },
      {
       "expr": "BlockManager_memory_maxOffHeapMem_MB{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Max Off Heap Memory (MB)"
      },
      {
       "expr": "BlockManager_memory_maxOnHeapMem_MB{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Max On Heap Memory (MB)"
      },
      {
       "expr": "BlockManager_memory_remainingMem_MB{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Remaining Memory (MB)"
      }
     ]
    },
    {
     "title": "Block Manager Disk Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "BlockManager_disk_diskSpaceUsed_MB{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Disk Memory (MB)"
      }
     ]
    }
   ]
  },
  {
   "title": "Hive External Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hive External Catalog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "HiveExternalCatalog_fileCacheHits{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "File Cache Hits"
      },
      {
       "expr": "HiveExternalCatalog_filesDiscovered{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "File Discovered"
      },
      {
       "expr": "HiveExternalCatalog_hiveClientCalls{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Client Calls"
      },
      {
       "expr": "HiveExternalCatalog_parallelListingJobCount{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Parallel Listing Jobs"
      },
      {
       "expr": "HiveExternalCatalog_partitionsFetched{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Partitions Fetched"
      }
     ]
    }
   ]
  },
  {
   "title": "Dag Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DAG Schedule Jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "DAGScheduler_job_activeJobs{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "Active Jobs"
      },
      {
       "expr": "DAGScheduler_job_allJobs{job=\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
       "legendFormat": "All Jobs"
      }
     ]
    },
    {
     "title": "Stages Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "DAGScheduler_stage_failedStages{role=\"driver\", job=\"$spark_job_id\"}",
       "legendFormat": "Failed Stages"
      },
      {
       "expr": "DAGScheduler_stage_runningStages{role=\"driver\", job=\"$spark_job_id\"}",
       "legendFormat": "Running Stages"
      },
      {
       "expr": "DAGScheduler_stage_waitingStages{role=\"driver\", job=\"$spark_job_id\"}",
       "legendFormat": "Waiting Stages"
      }
     ]
    }
   ]
  },
  { "title": "Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JVM Executor Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ExecutorMetrics_DirectPoolMemory{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "Direct Pool Memory"
    },
    {
     "expr": "ExecutorMetrics_JVMHeapMemory{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "JVM Heap Memory"
    },
    {
     "expr": "ExecutorMetrics_JVMOffHeapMemory{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "JVM Off Heap Memory"
    },
    {
     "expr": "ExecutorMetrics_OffHeapExecutionMemory{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "JVM Off Heap Execution Memory"
    },
    {
     "expr": "ExecutorMetrics_OnHeapStorageMemory{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "JVM On Heap Storage Memory"
    },
    {
     "expr": "ExecutorMetrics_OnHeapExecutionMemory{role=\"driver\", job=\"$spark_job_id\"}",
     "legendFormat": "JVM On Heap Execution Memory"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Executor Read and Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "executor_bytesRead{role=\"executor\", job=\"$spark_job_id\"}",
     "legendFormat": "Bytes Reads (#Executor {{number}})"
    },
    {
     "expr": "executor_bytesWritten{role=\"executor\", job=\"$spark_job_id\"}",
     "legendFormat": "Bytes Written (#Executor {{number}})"
    }
   ]
  },
  {
   "title": "Cpu Time Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(executor_cpuTime{role=\"executor\", job=\"$spark_job_id\"}[$__interval])",
     "legendFormat": "CPU time #{{number}}"
    }
   ]
  },
  {
   "title": "Executors Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(executor_runTime{role=\"executor\", job=\"$spark_job_id\"}[$__rate_interval])",
     "legendFormat": "Runtime (Executor #{{number}})"
    }
   ]
  }
 ]
}